### ISSUE TITLE
donot have files 

### ISSUE THREAD

**Issue by silenceghost** [apl-ocean-engineering/rqt_sonar_image_view#1]
there are two files in image_view.cpp have been lose, one of them is <sonar_image_proc/log_sonar_image_msg_interface.h> the other is <sonar_image_proc/sonar_image_msg_interface.h> where can I get them , thank u for your anwser

**Comment by amarburg** [comment]
[sonar_image_proc](https://github.com/apl-ocean-engineering/sonar_image_proc) must also be in your catkin workspace.

**Comment by silenceghost** [comment]
yep I have already put sonar_image_proc in my workplace ,but I do not have these two files in my sonar_image_procf folder lol

**Comment by silenceghost** [comment]
thank you very much for the anwser

**Comment by amarburg** [comment]
Ah, I see.  I used features that are in the [feature/logscale](https://github.com/apl-ocean-engineering/sonar_image_proc/pull/18) branch.   In the short term, use that branch of sonar_image_proc.   We should be pulling that code into the main branch in the next few days...

**Comment by lauralindzey** [comment]
Closing issue -- branch has been merged, so problem should have been resolved.
